name: Build

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: gulp bundle
